version: '{build}'
max_jobs: 1
image: WMF 5
clone_depth: 5
branches:
  only:
  - master

environment:
  au_version:
  au_push: true

  github_user_repo: Elderry/chocolatey-packages
  github_api_key:
    secure: fkLx9hbl6VRx9yna3ZDFKJ6hQxYmVMnRz6BqQF04x+4kOMhMFLWgYPvwRw+Ozq7n

  mail_user: Elderry@outlook.com
  mail_pass:
    secure: FNu3qrZ7Vp3deBbbDToJv3uAyqftcGCA34AO2B8XWVc=
  mail_server: smtp-mail.outlook.com
  mail_port: 587
  mail_enablessl: true

  gist_id: 687b1756f34c3b9f913dfb64ed3e2ca4

  api_key:
    secure: 267aa8d1-3e6e-45a8-be9d-9e4e6113a579
    
  expressvpn_license_key:
    secure: BQH2A9VaqoFX0jCi+rldcEtMKtn2M2KnFjaa4FuTpZ8lHozO/r4nxz3r9ywBfXWv

init:
- git config --global user.email "chocolatey@realdimensions.net"
- git config --global user.name  "Chocolatey"
- git config --global core.safecrlf false

install:
- ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
- ps: $PSVersionTable
- ps: |
    $x=$null; $is_branch = ($Env:au_version -ne $null) -and ([version]::TryParse($Env:au_version, [ref]$x) -eq $false)
    if ($is_branch) {
        pushd ..
            git clone -q https://github.com/majkinetor/au.git
            cd au
            git fetch
            git checkout -q $Env:au_version
            ./build.ps1 -Install -NoChocoPackage
        popd
    } else {
        Install-PackageProvider -Name NuGet -Force
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted

        $params = @{ Name = 'au' }
        if ( $Env:au_version -ne $null ) { $params.MinimumVersion = $Env:au_version }
        Install-Module @params

        Get-Module au -ListAvailable | select Name, Version
    }

build_script:
- ps: |
    ./au/update_all.ps1

artifacts:
- path: au/update_info.xml
- path: au/Update-AUPackages.md

notifications:
- provider: Email
  to: $(mail_user)
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
